version: '3.8'

services:
  backend:
    image: kap04ka/backend
    restart: always
    ports:
      - "5020:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  front:
    image: kap04ka/front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://localhost:5020/"
